EMGproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views # Import django Login Views; import Views always *as Variable* 
from users import views as user_views # import views.py from users-app as user_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='users-register'), 
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
    path('profile/', user_views.profil, name='users-profile'),
    path('staff_profile/', user_views.staff_profil, name='users-staff_profile'),
    path('', include('game.urls')), # include the game.urls file
    path('bidding/', user_views.bidding, name='users-bidding'),
    path('staff_new_game/', user_views.staff_new_game, name='users-staff_new_game'),
    path('join_game/', user_views.join_game, name='users-join_game'),
    path('waiting_room/', user_views.waiting_room, name='users-waiting_room'),
    path('ready_room/', user_views.ready_room, name='users-ready_room'),
    path('overview/', user_views.overview, name='users-overview'),
    path('profile/get_dynamic_content/', user_views.get_dynamic_content, name='get_dynamic_content'),
    path('profile/get_dynamic_content_decommission/', user_views.get_dynamic_content_decommission, name='get_dynamic_content_decommission'),
]

game/models.py
from django.db import models

# Generation Technology Data
class tech(models.Model):
    technology = models.CharField(max_length=30, unique=True) # Generation Technologies
    capacity = models.IntegerField(default=0) # Capacity per unit (MW)
    investment_cost = models.IntegerField() # Investment cost per unit 
    build_time = models.IntegerField() # Unit Build time in rounds
    operation_time = models.PositiveIntegerField() # Unit operation time in rounds
    fixed_cost = models.PositiveIntegerField(default=0) # Fixed cost per unit per round
    fuel_cost = models.DecimalField(decimal_places=2, max_digits=10) # Fuel cost per MWh produced
    carbon_content = models.DecimalField(decimal_places=2, max_digits=10) # Carbon content per MWh in tCO2
    default_amount = models.PositiveIntegerField(default=0) # Specified amount of units each player owns at the start of the game

    def __str__(self):
        return str(self.technology)

# Game sessions
class sessions(models.Model):
    name = models.CharField(max_length=30, unique=True)
    ready = models.BooleanField(default=False) # True= the game has started and is running; False= the game has not yet started
    variables = models.CharField(max_length=30, default='game_variables') # Chosen scenario
    final = models.BooleanField(default=False) # True= the game has finished (round=max_round); False= game has not yet finished (round<max_round)

    def __str__(self):
        return str(self.name)

# Basic Settings and Variables
class settings(models.Model):
    name = models.CharField(max_length=30)
    value = models.DecimalField(decimal_places=2, max_digits=20)
    game = models.ForeignKey(sessions, on_delete=models.CASCADE, to_field="name")

    def __str__(self):
        return str(self.name)

# Demand & Capacity Factors 
class demand_cf(models.Model):
    demand = models.IntegerField() # Demand per player (MW)
    cf_wind = models.DecimalField(decimal_places=2, max_digits=3)
    cf_pv = models.DecimalField(decimal_places=2, max_digits=3)
    round = models.IntegerField()
    key = models.CharField(max_length=30, default='game_variables') # key which describes the scenario

    class Meta:
        constraints = [
            models.UniqueConstraint(fields = ['round', 'key'], name = 'unique_set') # These fields have to be unique as a set
        ]

# Database for backup variables, used to save price history and installed capacities
class backup(models.Model):
    game = models.ForeignKey(sessions, on_delete=models.CASCADE, to_field="name")
    name = models.CharField(max_length=30)
    value = models.DecimalField(decimal_places=2, max_digits=20, null=True)
    round = models.IntegerField()

users/models.py
from django.db import models
from django.contrib.auth.models import User
from game.models import (
    tech,
    sessions,
    )

# User profiles
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Foreign Key to the User model
    budget = models.DecimalField(decimal_places=2, max_digits=100, default=0.00)
    revenue = models.DecimalField(decimal_places=2, max_digits=100, default=0.00)
    profit = models.DecimalField(decimal_places=2, max_digits=100, default=0.00)
    total_cost = models.DecimalField(decimal_places=2, max_digits=100, default=0.00)
    joined_game = models.ForeignKey(sessions, on_delete=models.SET_NULL, to_field="name", db_column="name", blank=True, null=True) # Name of the joined Game
    ready = models.BooleanField(default=False) # Truie= player is ready for the next round; False= player is not yet ready
    
    def __str__(self):
        return f'{self.user.username} Profile'

# User generation system    
class generation_system(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Foreign Key to the User model
    technology = models.ForeignKey(tech, on_delete=models.CASCADE, to_field="technology", db_column="technology") # Generation Technology, Foreign Key to the tech model
    capacity = models.IntegerField(default=0) # Capacity in MW
    until_decommissioned = models.PositiveIntegerField(default=0) # Remaining operational periods

    def __str__(self):
        return f'Sys_ID: {self.id}, User: {self.user.username}, Tech: {self.technology} ' 

# User construction orders
class construction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Foreign Key to the User model
    technology = models.ForeignKey(tech, on_delete=models.CASCADE, to_field="technology", db_column="technology") # Generation Technology, Foreign Key to the tech model
    until_constructed = models.PositiveIntegerField(default=0) # Remaining build time in rounds

    def __str__(self):
        return f'Cons_ID:{self.id}, User: {self.user.username}, Tech: {self.technology}' 

# User bids
class bids(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Foreign Key to the User model
    technology  = models.ForeignKey(tech, on_delete=models.CASCADE, to_field="technology", db_column="technology") # Chosen Technology, Foreign Key to the tech model
    price = models.DecimalField(decimal_places=2, max_digits=10)   # €/MWh
    amount = models.DecimalField(decimal_places=2, max_digits=10)  # MW

    def __str__(self):
        return f'Bid_ID: {self.id}, User: {self.user.username}, Tech: {self.technology}, Price: {self.price}, Capacity: {self.amount}'

# Accepted bids/ merit order
class bids_meritorder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Foreign Key to the User model
    technology  = models.ForeignKey(tech, on_delete=models.CASCADE, to_field="technology", db_column="technology") # Chosen Technology, Foreign Key to the tech model
    price = models.DecimalField(decimal_places=2, max_digits=10)  # €/MWh
    amount = models.DecimalField(decimal_places=2, max_digits=10)  # MW





users/views.py
# users views
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required # login required decorator
from django.contrib.admin.views.decorators import staff_member_required # staff member required decorator
import pandas as pd # pandas package used for data export
# plotly package used to diplay graphs
import plotly.express as px
import plotly.offline as opy
import plotly.graph_objs as go
# Import forms
from .forms import (
    UserRegisterForm, 
    ConstructionForm, 
    DecommissionForm, 
    BiddingForm,      
    SettingsForm,     
    NextRoundForm,    
    DeleteBidForm,
    NewGameSessionForm,
    HostGameSessionForm,
    JoinGameSessionForm,
    StartEndGameSessionForm,
    DeleteGameSessionForm,
    PlayerReadyForm,
    RemovePlayerForm,
    ExportForm,
    EnforceReadyForm,
    )
# Import models
from .models import ( 
    generation_system, 
    Profile,           
    construction,      
    bids,              
    bids_meritorder,
    )
from game.models import (
    tech,       
    settings,   
    sessions,
    demand_cf,
    backup,
    )
from django.contrib.auth.models import User

from django.db.models.signals import post_save  # Importing post save signal
from django.dispatch import receiver # Signal receiver decorator
from django.db.models import Sum, Count
from decimal import Decimal

# User Register view
def register(request):
    if request.method == "POST":
        # Register new user (Form)
        form = UserRegisterForm(request.POST)
        if form.is_valid(): 
            form.save() 
            username = form.cleaned_data.get("username")
            messages.success(request, f'Hello {username}, Your Accout has been created! You ar now able to log in.') # Pop-up message
            return redirect('users-profile') # Redirect user
    else:
        form = UserRegisterForm()
    # Define HTML variables
    context = {
        "title": "Register",
        'form': form,
    }
    return render(request, 'users/register.html', context)

# Create a Player Profile for each new registered User
@receiver(post_save, sender=User) # Get signal from user creation
def user_created_handler(sender, instance, created,*args,**kwargs):
    if created:
        # Set initial profile values
        Profile(user=instance, budget=0, revenue=0, profit=0, total_cost=0).save()       

# Profile Page view
@login_required # Decorator, only logged in users can access profile page
def profil(request):
    # Redirect gamemaster
    if request.user.is_staff:
        return redirect('users-staff_profile')
    # Get data
    profile = Profile.objects.get(user_id = request.user.id)
    joined_game = Profile.objects.values_list('joined_game', flat=True).get(user_id = request.user.id)
    # User can only enter profile if the joined a game and the game has started
    if profile.joined_game is not None:
        if not profile.ready and sessions.objects.get(name = joined_game).ready:
            current_game = sessions.objects.get(name = joined_game)
            # Redirect players if the game is over
            if current_game.final:
                messages.success(request, f'The Game has ended!')
                return redirect('users-overview')
            # Get data
            cap = generation_system.objects.filter(user_id = request.user.id)                       
            current_round = settings.objects.get(game_id = joined_game, name = 'round').value
            cf_wind = demand_cf.objects.get(key = current_game.variables, round = current_round).cf_wind
            cf_pv = demand_cf.objects.get(key = current_game.variables, round = current_round).cf_pv
            user_bids = bids.objects.filter(user_id = request.user.id)        
            # Decommission Generators (Form)
            form_d = DecommissionForm()
            if 'delete_generator' in request.POST: # Check for the forms hidden boolean
                if request.method == "POST":
                    form_d = DecommissionForm(request.POST)
                    if form_d.is_valid():
                        units = form_d.cleaned_data['units']
                        technology = form_d.cleaned_data['techs']
                        # Order units by lifetime rounds left, then delete the first x entries where x = the chosen amount of units
                        gen = generation_system.objects.filter(user = request.user, technology = technology).order_by('until_decommissioned')[:units]
                        # Cannot delete more Generators than exist
                        if len(gen) < units:
                            messages.warning(request, f'You currently do not own {units} {technology} units in your generation system!')
                            return redirect('users-profile')
                        # Calculate player capacities
                        bid_cap = (user_bids.filter(technology = technology).aggregate(Sum('amount')))['amount__sum']
                        if str(technology) == 'Wind':
                            cap = (generation_system.objects.filter(user_id = request.user.id, technology = technology).aggregate(Sum('capacity')))['capacity__sum'] * cf_wind
                        elif str(technology) == 'Solar':
                            cap = (generation_system.objects.filter(user_id = request.user.id, technology = technology).aggregate(Sum('capacity')))['capacity__sum'] * cf_pv
                        elif str(technology) != 'Solar' and str(technology) != 'Wind':
                            cap = (generation_system.objects.filter(user_id = request.user.id, technology = technology).aggregate(Sum('capacity')))['capacity__sum']
                        # You cannot delete generators if the capacity is already placed in a bid
                        if cap is not None and bid_cap is not None:
                            remaining_cap = cap - bid_cap
                            if str(technology) == 'Wind':
                                delete_cap = (gen.aggregate(Sum('capacity')))['capacity__sum'] * cf_wind
                            elif str(technology) == 'Solar':
                                delete_cap = (gen.aggregate(Sum('capacity')))['capacity__sum'] * cf_pv
                            elif str(technology) != 'Solar' and str(technology) != 'Wind':
                                delete_cap = (gen.aggregate(Sum('capacity')))['capacity__sum']
                            if delete_cap > remaining_cap:
                                messages.warning(request, f'The chosen units are already scheduled for production! Please edit your placed bids until enough remaining capacity is available.')
                                return redirect('users-profile')
                        # Delete Generators
                        gens = gen.values_list('id', flat=True)
                        generation_system.objects.filter(id__in = gens).delete()
                        messages.success(request, f'Decommission Successfull!')
                        return redirect('users-profile')
                    else:
                        form_d = DecommissionForm()
            # Construct Generators (Form)
            form_c = ConstructionForm()
            if 'add_generator' in request.POST: # hidden boolean 
                if request.method == "POST":
                    form_c = ConstructionForm(request.POST)
                    form_c.instance.user = request.user # Pass user instance (logged in user) to form
                    p = Profile.objects.get(user_id=request.user)
                    # Check if players budget is sufficient
                    if form_c.is_valid() and (p.budget >= (tech.objects.get(technology=form_c.instance.technology).investment_cost * int(form_c.data['amount']))): 
                        t = tech.objects.get(technology=form_c.instance.technology)
                        # Get build_time from tech DB, has to be after 'form.is_valid()' otherwise error 'RelatedObjectDoesNotExist'--> Form entries only accessible after validation
                        form_c.instance.until_constructed = t.build_time
                        instance = form_c.save(commit=False) # Calling save with commit=False returns an instance that is not saved to the database
                        for i in range(int(form_c.data['amount'])): # Loop over the chosen amount of units
                            instance.id = None # By setting the primary key to None, a new object will be saved each time
                            instance.save() 
                            p.budget -= t.investment_cost   # Update budget
                            p.save()                        
                        messages.success(request, f'Construction Order Successfull!')
                        return redirect('users-profile')
                    else:
                        messages.warning(request, f'Not enough funds!')
                        form_c = ConstructionForm()  
                else:
                    form_c = ConstructionForm()
            # Change Player "ready" state (Form)
            form_pr = PlayerReadyForm()
            if 'player_ready' in request.POST: # hidden boolean
                if request.method == "POST": 
                    form_pr = PlayerReadyForm(request.POST)
                    if form_pr.is_valid():
                        profile.ready = not profile.ready
                        profile.save()
                        return redirect('users-ready_room')
                    else:
                        messages.warning(request, f'Error! Something went wrong.')
                        form_pr = PlayerReadyForm() 
            # Get data for templates

users/templates/users/bidding.html
{% extends "game/base.html" %}
{% load crispy_forms_tags %} <!--import Django Crispy Forms-->
{% load custom_tags %}
{% load static %}
{% block content %}
<!-- import jQuery -->
<!-- <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>  -->

<h2>Step Three: Bidding</h2>
<h4>
    You can sell your available generation capacity at the power exchange by placing bids.<br>
    At the end of the round the market will be cleared: Starting with the lowest price, bids will be accepted until the demand is satisfied.
    All accepted bids will receive the clearing price!
</h4>
<br>
    <!-- Market Overview -->
    <h4>Demand forecast</h4>
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Demand (current round)</th>
            <th scope="col">Demand t+1</th>
            <th scope="col">Demand t+2</th>
            </tr>
        </thead>
        <tbody>
            <tr scope="row">
                <td>{{ demand }} MWh</td>
                <td>{{ demand_forecast_plus1 }} MWh</td> 
                <td>{{ demand_forecast_plus2 }} MWh</td> 
            </tr>
        </tbody>
    </table> 

    <h4 class="d-inline-flex gap-1">Technology Data:</h4>
    <p class="d-inline-flex gap-1">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Click here to view the detailed cost and capacity data for each generation technology unit
        </button>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                    <th scope="col">Technology</th>
                    <th scope="col">Capacity per Unit [MW]</th>
                    <th scope="col">Investement Cost per Unit [€]</th>
                    <th scope="col">Build Time [t]</th>
                    <th scope="col">Operation Time [t]</th>
                    <th scope="col">Fixed Cost [€/Unit]</th>
                    <th scope="col">Fuel Cost [€/MWh_el]</th>
                    <th scope="col">Carbon Content [t/MWh_el]</th>
                    <th scope="col">Carbon Cost [€/MWh_el]</th>
                    <th scope="col" style="border-left: 5px dashed;">Total Variable Cost [€/MWh_el]</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for data in datas %}
                    <tr scope="row">
                        <td><b>{{ data.technology }}</b></td>
                        <td>{{ data.capacity }}</td> 
                        <td>{{ data.investment_cost }}</td> 
                        <td>{{ data.build_time }}</td> 
                        <td>{{ data.operation_time }}</td> 
                        <td>{{ data.fixed_cost }}</td> 
                        <td>{{ data.fuel_cost }}</td> 
                        <td>{{ data.carbon_content }}</td>
                        <td>{% multiply data.carbon_content carbon_price as carbon_cost %} {{ carbon_cost|floatformat:2 }}</td>
                        <td>{% add carbon_cost data.fuel_cost as total_variable_cost %} {{ total_variable_cost|floatformat:2 }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <h3 class="mt-2">Total Available Capacity</h3>
    <!--Kapazitäten Kummuliert Tabelle-->
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Technology</th>
            <th scope="col">Total available Capacity (CF applied)</th>
            <th scope="col">Remaining available Capacity for bidding </th>
            </tr>
        </thead>
        <tbody>
            {% for key, value in capsum.items %} 
            <tr scope="row">
                <td>{{ key }}</td>
                <td>{{ value }} MW</td>
                <td>{{ remaining_cap|dict_key:key }} MW</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>


    <legend class="border-bottom mb-4">
        Place Bid: Choose a generation technology and enter the price and the capacity. <br>
    </legend>
    <!-- Select Technology Image Buttons -->
    <div class="button-container d-inline-block me-2" id="select-button-coal" data-technology="Coal">
        <button class="btn btn-md btn-outline-secondary">
            <img src="{% static '/images/coal.jpg' %}" class="img-fluid" style="height: 60px; width: auto;">
        </button>
    </div>
    <div class="button-container d-inline-block me-2" id="select-button-wind" data-technology="Wind">
        <button class="btn btn-md btn-outline-secondary">
            <img src="{% static '/images/wind.jpg' %}" class="img-fluid" style="height: 60px; width: auto;">
        </button>
    </div>
    <div class="button-container d-inline-block me-2" id="select-button-solar" data-technology="Solar">
        <button class="btn btn-md btn-outline-secondary">
            <img src="{% static '/images/solar.jpg' %}" class="img-fluid" style="height: 60px; width: auto;">
        </button>
    </div>
    <div class="button-container d-inline-block me-2" id="select-button-nuclear" data-technology="Nuclear">
        <button class="btn btn-md btn-outline-secondary">
            <img src="{% static '/images/nuclear.jpg' %}" class="img-fluid" style="height: 60px; width: auto;">
        </button>
    </div>
    <div class="button-container d-inline-block me-2" id="select-button-ccgt" data-technology="CCGT">
        <button class="btn btn-md btn-outline-secondary">
            <img src="{% static '/images/ccgt.jpg' %}" class="img-fluid" style="height: 60px; width: auto;">
        </button>
    </div>

    <!-- Select Technology JS -->
    <script>
        $(document).ready(function () {
            // Handle the click event of the specific buttons
            $('#select-button-coal, #select-button-wind, #select-button-solar, #select-button-nuclear, #select-button-ccgt').on('click', function () {
                // Set the selected technology based on the button clicked
                var selectedTechnology = $(this).data('technology');
                $('#id_technology').val(selectedTechnology);

                // Trigger the change event to update dynamic content
                $('#id_technology').trigger('change');
            });
        });
    </script>

    <!-- Formular Gebotsabgabe -->
    <div>
        <form method="POST">
            <fieldset class="form-group">
                {% csrf_token %}
                {{ form_bidding|crispy }} 
            </fieldset>
            <div class="form-group mt-2">
                <button class="btn btn-outline-info" type="submit" onclick="return confirm('Are you sure?');" name="bidbtn">Place Bid</button>
            </div>
        </form>
    </div>
    <br>

    <div class="accordion" id="accordionBids">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <strong><h5>Bids placed this round</h5></strong>
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionBids">
                <div class="accordion-body">
                    <!--Bidding Table-->
                    <table class="table table-striped">
                        <thead>
                            <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Technology</th>
                            <th scope="col">Price</th>
                            <th scope="col">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for b in bids %}
                            <tr scope="row">
                                <td>{{ b.id}}</td>
                                <td>{{ b.technology}}</td>
                                <td>{{ b.price}} €/MWh</td>  
                                <td>{{ b.amount}} MW</td> 
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Formular Gebote Löschen -->
    <div>
        <form method="POST">
            <fieldset class="form-group">
            {% csrf_token %}
                <legend class="border-bottom mb-4">Delete Bid: Changed your mind? You can delete any bids placed this round.</legend>
                {{ form_deletebid|crispy }} 
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info mt-2" type="submit" onclick="return confirm('Are you sure?');" name="dltbidbtn">Confirm Deletion</button>
            </div>
        </form>
    </div>

    <br>
    <h2>Step Four: Ready up!</h2>
    <!-- Ready for next Round -->
    <div style="clear:both">
        <form method="POST" >
            <fieldset class="form-group">
            {% csrf_token %}
                <legend class="border-bottom mb-2">
                    If you are done and ready for the next round, please press the button below!
                </legend>
                {{ form_playerready|crispy }} 
            </fieldset>
            <div class="form-group">
                <button class="btn btn-success mt-2 mb-4" type="submit" onclick="return confirm('Are you sure? Once you are ready, you can not make anymore actions until the next round!');" name="constructbtn">
                    I am Ready!
                    <!-- Icon -->
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                        <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                    </svg>
                </button>
                <!-- Go Back Button -->
                <a  class="btn btn-secondary mt-2 mb-4" role="button" onclick="history.back()" style="float:right; ">Go Back</a>
            </div>
        </form>
    </div>

    
    
{% endblock content%}

users/templates/users/join_game.html
{% extends "game/base.html" %}
{% load custom_tags %}
{% load crispy_forms_tags %} <!--import Django Crispy Forms-->
{% block content %}

<h2>Please join a Game from the list below and wait for instructions</h2>
<h3>You can only enter a game if it has not already started</h3>
<br>
<a  class="btn btn-light mb-4" role="button" onClick="window.location.reload();">Refresh List</a>
    <!--Games Tabelle-->
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Game ID</th>
                <th scope="col">Name </th>
                <th scope="col">Game has already started</th>
            </tr>
        </thead>
        <tbody>
            {% for g in game %}
            <tr scope="row">
                <td>{{ g.id}}</td>
                <td>{{ g.name}}</td>
                <td>{{ g.ready}}</td> 
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Join Game Form -->
    <div>
        <form method="POST">
            <fieldset class="form-group mb-4">
            {% csrf_token %}
                <legend class="border-bottom mb-4"></legend>
                {{ form_joingame|crispy }} 
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" onclick="return confirm('Are you sure?');">Join Game</button>
            </div>
        </form> 
    </div>

{% endblock content%}

users/templates/users/login.html
{% extends "game/base.html" %}
{% load crispy_forms_tags %} <!--import Django Crispy Forms-->
{% block content %}

<div>
    <form method="POST">
        {% csrf_token %} <!--django braucht csrf token für Sicherheit, ohne funktioniert dieses Form nicht-->
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login</legend>
            {{ form|crispy }} 
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an Account? <a class="ml-2" href="{% url 'users-register' %}">Sign Up</a>
        </small>
    </div>
</div>
        
{% endblock content%}

users/templates/users/logout.html
{% extends "game/base.html" %}

{% block content %}

<h2>You have been logout out!</h2>

<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'users-login' %}">Log In Again</a>
    </small>
</div>

        
{% endblock content%}

users/templates/users/ready_room.html
{% extends "game/base.html" %}
{% load custom_tags %}
{% load crispy_forms_tags %} <!--import Django Crispy Forms-->
{% block content %}
<meta http-equiv="refresh" content="10">

<div class="d-inline-block">
    <h1>Please wait for the next round to start!</h1>
</div>
<div class="d-inline-block ms-4">
    <div class="spinner-border text-success" role="status"> </div>
</div>


{% endblock content%}